# Generated by Django 5.1.5 on 2025-01-21 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The topic or title of the story.', max_length=255)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('word_limit', models.PositiveIntegerField(default=500)),
                ('voice_interaction', models.BooleanField(default=True)),
                ('include_quiz', models.BooleanField(default=True, help_text='Whether a quiz should follow the story.')),
                ('number_of_questions', models.PositiveIntegerField(default=20)),
                ('question_type', models.CharField(default='short-answer', editable=False, max_length=50)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
