# Generated by Django 5.1.5 on 2025-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0003_alter_story_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='continuation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
