# Generated by Django 5.1.5 on 2025-01-31 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0004_story_continuation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('current_question', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='storybook.story')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
