# Generated by Django 5.1.5 on 2025-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0005_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
