# Generated by Django 5.1.5 on 2025-02-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0008_alter_story_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_answers',
            field=models.JSONField(blank=True, help_text="Stores user's answers and their correctness per question.", null=True),
        ),
    ]
